Server test fixes
Mobar-Coder/Secret-Bundestag-Server pull request #19
Opened 2020-12-12 12:21 UTC by Timmifixedit

2020-12-12 16:49 UTC, aul12 requested changes

2020-12-12 16:49 UTC, aul12 commented on CMakeLists.txt
> +    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ")#-fsanitize=address -fno-omit-frame-pointer")
...

2020-12-14 08:10 UTC, Timmifixedit commented on CMakeLists.txt
> +    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ")#-fsanitize=address -fno-omit-frame-pointer")
Ja das war drin, weil mans sonst nicht auf den Carolo PCs laufen lassen kann. Mach ich wieder raus

2020-12-15 14:18 UTC, aul12 approved these changes

2020-12-15 14:18 UTC, merged