Feature/rule set
Mobar-Coder/Secret-Bundestag-Server pull request #23
Opened 2020-12-14 23:05 UTC by jonas-merkle

2020-12-14 23:19 UTC, aul12 requested changes

2020-12-14 23:19 UTC, aul12 commented on src/gamelogic/gamemodel/EventTrigger.hpp
> +            std::shared_ptr<AbstractEventTrigger> lhs;
private?

2020-12-14 23:19 UTC, aul12 commented on src/gamelogic/gamemodel/EventTrigger.cpp
> +        return false;
Kann das schon implementiert werden?

2020-12-14 23:19 UTC, aul12 commented on src/gamelogic/gamemodel/SingleCardEventTrigger.cpp
> +        return false;
S.o.

2020-12-14 23:19 UTC, aul12 commented on src/gamelogic/gamemodel/SingleCardEventTrigger.hpp
> +            std::size_t threshold{};
S.o.

2020-12-14 23:21 UTC, jonas-merkle commented on src/gamelogic/gamemodel/EventTrigger.cpp
> +        return false;
nop da fehlt noch zu viel im Environment

2020-12-15 11:09 UTC, aul12 commented on src/gamelogic/gamemodel/EventTrigger.cpp
> +        return false;
Aber der EventTrigger nutzt ja nur jeweils `lhs`, `rhs` und das Prädikat und gibt das Environment nur weiter

2020-12-15 12:22 UTC, pmo73 requested changes

2020-12-15 12:22 UTC, pmo73 commented on src/gamelogic/enum/EventType.hpp
> +            Execution, InvestigateLoyalty, Veto, PolicyPeek, SpecialElection
Meines Wissens nach sind die Typen in einem Enum alle UPPER_SNEAK_CASE

2020-12-15 12:22 UTC, pmo73 commented on src/gamelogic/enum/TriggerComparator.hpp
> +            Equal, Less, Greater, Unequal
Meines Wissens nach sind die Typen in einem Enum alle UPPER_SNEAK_CASE

2020-12-15 12:22 UTC, pmo73 commented on src/gamelogic/enum/TriggerCompositor.hpp
> +            And, Or
Meines Wissens nach sind die Typen in einem Enum alle UPPER_SNEAK_CASE

2020-12-15 13:50 UTC, Timmifixedit requested changes

2020-12-15 13:50 UTC, Timmifixedit commented on src/gamelogic/gamemodel/AbstractEventTrigger.hpp
> +            virtual auto triggered(std::shared_ptr<const Environment> environment) -> bool = 0;
Man könnte den shared_ptr zusätzlich als const ref übergeben. Ist aber nicht so schlimm

2020-12-15 13:50 UTC, Timmifixedit commented on src/gamelogic/gamemodel/EventTrigger.cpp
> +                break;
Vllt noch nen default case, indem eine not-implemented exception fliegt. Falls man mal später neue Möglichkeiten hinzufügt und vergisst die zu implementieren

2020-12-15 13:50 UTC, Timmifixedit commented on src/gamelogic/gamemodel/SingleCardEventTrigger.cpp
> +                break;
Hier auch bitte noch einen default case mit exception

2020-12-15 14:17 UTC, aul12 approved these changes
Meine Anmerkungen passen, mach halt noch die Sachen von Tim

2020-12-15 15:02 UTC, Timmifixedit approved these changes

2020-12-15 15:03 UTC, Timmifixedit commented
Björns Anmerkungen wurden ja eingebaut, oder? Dann würde ich das nämlich mergen

2020-12-15 15:04 UTC, merged