Environment implemented, not tested
Mobar-Coder/Secret-Bundestag-Server pull request #24
Opened 2020-12-15 12:24 UTC by pmo73

2020-12-22 21:07 UTC, Timmifixedit requested changes

2020-12-22 21:07 UTC, Timmifixedit commented on src/gamelogic/gamemodel/Board.cpp
> +    auto Board::getCurrentOffices(Office office) const -> std::optional<std::shared_ptr<const Player>> {
Vielleicht eher getPlayerinCurrentOffice oder so?

2020-12-22 21:07 UTC, Timmifixedit commented on src/gamelogic/gamemodel/Board.cpp
> +    auto Board::getPastOffices(Office office) const -> std::optional<std::shared_ptr<const Player>> {
Siehe oben

2020-12-22 21:07 UTC, Timmifixedit commented on src/gamelogic/gamemodel/Board.cpp
> +    void Board::setCurrentOffices(Office office, const std::shared_ptr<const Player> &player) {
setCurrentOffice ? Singular

2020-12-22 21:07 UTC, Timmifixedit commented on src/gamelogic/gamemodel/Board.cpp
> +    auto Board::getPastOffices() -> std::unordered_map<Office, std::optional<std::shared_ptr<const Player>>> & {
Brauchen wir das mit nicht const ref?

2020-12-22 21:07 UTC, Timmifixedit commented on src/gamelogic/gamemodel/Board.hpp
> +            std::unordered_map<Office, std::optional<std::shared_ptr<const Player>>> currentOffices;
Der value type von der Map muss doch nicht optional sein, oder? Wenn es das Office nicht gibt, kann man es ja einfach aus der Map entfernen

2020-12-22 21:07 UTC, Timmifixedit commented on src/gamelogic/gamemodel/CardRange.cpp
> +        for (std::size_t i = 0; i < tmp; i++) { //NOLINT
Warum jetzt nicht mehr als foreach. Und warum nur index 0?

2020-12-22 21:07 UTC, Timmifixedit commented on src/gamelogic/gamemodel/Environment.cpp
> +        board.setCurrentOffices(Office::PRESIDENT, this->players[0]);
Sollte besser zufällig ausgewählt werden

2020-12-22 21:07 UTC, Timmifixedit commented on src/gamelogic/gamemodel/Environment.cpp
> +        it->get()->setAlive(false);
Bitte checken ob it != end und ggf exception werfen

2020-12-22 21:07 UTC, Timmifixedit commented on src/gamelogic/gamemodel/Environment.cpp
> +    auto Environment::getBoard() const -> const Board & {
Brauchen wir das Board überhaupt nach draußen geben? Ihr schleift doch schon die ganze utility durch

2020-12-22 21:07 UTC, Timmifixedit commented on src/gamelogic/gamemodel/Player.cpp
>      void Player::setRole(Role playerRole) {
Fällt mir nur grad so auf: Wird die Rolle jemals geänfert?

2020-12-22 21:07 UTC, Timmifixedit commented on src/gamelogic/gamemodel/Player.cpp
>      void Player::setSessionId(size_t sessionId) {
Auch hier: Brauchen wir den setter?

2020-12-23 09:05 UTC, aul12 requested changes

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/Board.cpp
> +        if (it != currentOffices.end()) {
`cend`

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/Board.cpp
> +        if (it != pastOffices.end()) {
`cend`

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/Board.cpp
> +    auto Board::getPastOffices() -> std::unordered_map<Office, std::optional<std::shared_ptr<const Player>>> & {
Und wollen wir da überhaupt die gesamte Map rausgeben? Dann muss da der Nutzer wieder wissen wie die map zu verstehen ist...

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/Board.hpp
> +             *
Doc

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/CardRange.cpp
> +        for (std::size_t i = 0; i < tmp; i++) { //NOLINT
Und das NOLINT kann vermutlich raus

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/Environment.cpp
> +        return std::vector<std::shared_ptr<const Player>>(players.begin(), players.end());
`cbegin`, `cend`

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/Environment.cpp
> +        auto it = std::find(players.cbegin(), players.cend(), player);
Du kannst auch einfach players.find aufrufen

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/Environment.cpp
> +        if (player.has_value()) {
Für den Fall das kein Präsident existiert wird kein neuer ausgewählt, ist das absicht? Wenn ja vielleicht den Funktionsnamen dementsprechend anpassen

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/Environment.cpp
> +                if (std::distance(iterator_start, it) == 0) {
WIeso std::distance? `==` sollte doch auch reichen...

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/Environment.cpp
> +                    throw std::runtime_error("All Plyers have been killed!");
```suggestion
                    throw std::runtime_error("All Players have been killed!");
```

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/Environment.cpp
> +    auto Environment::getPresident() -> std::shared_ptr<const Player> {
Soll das eine Exception werfen? Wäre da nicht vielleicht ein optional sinnvoller?

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/Environment.cpp
> +        std::vector<std::shared_ptr<const Player>> result;
`std::copy_if`

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/Environment.hpp
> +             * @return the actual value of the election tracker
```suggestion
             * @return the current value of the election tracker
```
actual=tatsächlich, current=aktuell

2020-12-23 09:05 UTC, aul12 commented on src/gamelogic/gamemodel/Player.cpp
>      void Player::setSessionId(size_t sessionId) {
Gar nicht, die Beziehung Player<->Id sollte sich nicht ändern

2020-12-23 13:33 UTC, pmo73 commented on src/gamelogic/gamemodel/Environment.cpp
> +    auto Environment::getBoard() const -> const Board & {
Ja für die Tests

2020-12-23 13:42 UTC, pmo73 commented on src/gamelogic/gamemodel/Environment.cpp
> +        auto it = std::find(players.cbegin(), players.cend(), player);
Sicher dass es das bei std::vector gibt? Wird nicht vorgeschlagen?

2020-12-23 13:43 UTC, pmo73 commented on src/gamelogic/gamemodel/Environment.cpp
> +        if (player.has_value()) {
Die Idee war im Konstruktor direkt einen zu setzen, so dass immer einer ausgewählt sein muss wie es im Spiel auch ist, dann gibt es ja immer einen oder?

2020-12-23 13:44 UTC, pmo73 commented on src/gamelogic/gamemodel/Environment.cpp
> +    auto Environment::getPresident() -> std::shared_ptr<const Player> {
Wenn es immer einen Präsidenten gibt brauche ich da dann ein optional? Vllt dann lieber eine runtime exception, weil dann geht  ja alles schief?

2020-12-23 13:50 UTC, aul12 commented on src/gamelogic/gamemodel/Environment.cpp
> +    auto Environment::getPresident() -> std::shared_ptr<const Player> {
Wenn es immer einen Präsidenten gibt vielleicht einfach immer ein `assert(....has_value())`? Vor allem? Das sollte ja eigentlich nicht vorkommen

2020-12-23 15:12 UTC, Timmifixedit requested changes
Meine Anmerkung in der CardRange ist noch nicht resolved

2021-01-04 20:14 UTC, pmo73 commented on src/gamelogic/gamemodel/Environment.cpp
> +    auto Environment::getPresident() -> std::shared_ptr<const Player> {
Da wird ja eine Exception geschmissen wenn es nicht so ist?

2021-01-04 21:15 UTC, aul12 approved these changes

2021-01-04 21:16 UTC, merged