Messages
Mobar-Coder/Secret-Bundestag-Server pull request #27
Opened 2021-01-04 22:36 UTC by TarikEnderes

Restliche Messages implementiert

2021-01-05 10:13 UTC, aul12 requested changes

2021-01-05 10:13 UTC, aul12 commented on src/messages/GameEnd.cpp
> +// Created by timluchterhand on 12.12.20.
...

2021-01-11 20:47 UTC, Timmifixedit approved these changes, later dismissed

2021-01-11 20:47 UTC, pmo73 approved these changes, later dismissed

2021-01-18 20:52 UTC, aul12 approved these changes

2021-01-18 20:53 UTC, Timmifixedit approved these changes

2021-01-18 20:53 UTC, merged